[workspace]
members = ["libver"]
resolver = "3"

[package]
name = "verune"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["cargo"] }
libver = { version = "0.1.0", path = "./libver" }
ron = "0.12.0"
